name: CI/CD Pipeline Example
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Ruff Code Quality Validation
    runs-on: ubuntu-latest
    # steps:
    #   - name: Get Terraform Python Version
    #     id: terraform-python-version
    #     uses: dflook/terraform-version-extractor@v2
    #   - name: Setup Terraform
    #     uses: hashicorp/setup-terraform@v3
    #     with:
    #       terraform_version: ${{ steps.tf-version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get Python Version
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Set Up Environment
        uses: astral-sh/setup-uv@v5
      - name: Install Dependencies
        run: uv sync --all-groups
      - name: Lint with Ruff
        run: uv run ruff check .
      - name: Format with Ruff
        run: uv run ruff format --check .
  test:
      name: Run Pytest Validation
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Set Up Environment
          uses: astral-sh/setup-uv@v5
          with:
            python-version: "3.14"
        - name: Install Dependencies
          run: uv sync --all-groups
        - name: Run Tests with Pytest
          run: uv run pytest